### ISSUE TITLE
Could not autoload puppet/type/mac_plist_value

### ISSUE THREAD

**Issue by brownmike** [jaredjennings/puppet-mac_plist_value#1]
I am new to Puppet so I may be missing something. But I installed the module on my Puppet Master

```
user@puppet:/etc/puppetlabs/code/environments/production/modules$ sudo puppet module install jaredjennings-mac_plist_value
[sudo] password for user:
Notice: Preparing to install into /etc/puppetlabs/code/environments/production/modules ...
Notice: Downloading from https://forgeapi.puppetlabs.com ...
Notice: Installing -- do not interrupt ...
/etc/puppetlabs/code/environments/production/modules
└── jaredjennings-mac_plist_value (v0.3.0)
```

And I added this to my node definition

```
mac_plist_value { '/Users/admin/Library/Preferences/com.apple.Terminal.plist':
  key   => 'Default Window Settings',
  value => 'Pro'
}
```

And when I run `sudo puppet agent apply -t` on my node I get

```
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Evaluation Error: Error while evaluating a Resource Statement, Could not autoload puppet/type/mac_plist_value: no such file to load -- puppet/type/mac_plist_common_parameters at /etc/puppetlabs/code/environments/production/manifests/site.pp:35:3 on node test-puppet
```

Am I missing the way this is designed to work?

Thanks!

**Comment by jaredjennings** [comment]
@brownmike, sorry to leave you hanging - I thought I replied with a partial answer the same day but it's not here.

It could be that I've made the module wrong, but I can't figure it out without some more data from you. First, what version of Puppet are you running on the client and on the server? And second, did you run `puppet agent` or `puppet apply`? It doesn't seem clear from your post.

**Comment by brownmike** [comment]
Ah, sorry it was `puppet agent` that was a typo. Puppet version 4.2.1 on both server and client. I just tried it again on my local client with `puppet apply` and got the same error again.

Thanks for the response! I might try to dig into the source to see if I can figure this out since this is the only module I've found that can do what I'm looking for.

**Comment by brownmike** [comment]
Ugh. I wasn't including the module.

Interestingly enough, my example still doesn't work. But at least I'm getting an error from the module instead now.

Here's my test.pp file

```
include mac_plist_value

mac_plist_value { '/Users/mike/Library/Preferences/com.apple.Terminal.plist':
  key   => 'Default Window Settings',
  value => 'Pro'
}
```

And here's my terminal session. I did a defaults read on the key for that file just to verify its existence. The plist is in binary mode, not sure if that matters.

```
~/O/D/puppet-sandbox ❯❯❯ puppet --version                                                                                                                                          ⏎
4.2.2
~/O/D/puppet-sandbox ❯❯❯ puppet module install jaredjennings-mac_plist_value
Notice: Preparing to install into /Users/mike/.puppetlabs/etc/code/modules ...
Notice: Module jaredjennings-mac_plist_value 0.3.0 is already installed.
~/O/D/puppet-sandbox ❯❯❯ puppet apply --noop test.pp
Notice: Compiled catalog for mike.local in environment production in 0.28 seconds
Error: /Stage[main]/Main/Mac_plist_value[/Users/mike/Library/Preferences/com.apple.Terminal.plist]: Could not evaluate: no implicit conversion of nil into String
Notice: Applied catalog in 0.02 seconds
~/O/D/puppet-sandbox ❯❯❯ defaults read /Users/mike/Library/Preferences/com.apple.Terminal.plist 'Default Window Settings'
Homebrew
```

**Comment by jaredjennings** [comment]
It is quite interesting to me that you had to `include mac_plist_value` since that is an empty class. Perhaps this clues Puppet 4 in to the idea that you're going to use the plugin content in the module; I don't know.

Now, as to the implicit conversion of nil into String: I think you either have to 

``` puppet
    mac_plist_value { '/Users/mike/Library/Preferences/com.apple.Terminal.plist:Default Window Settings':
        value => 'Pro',
    }
```

or

``` puppet
    mac_plist_value { "set mike's terminal to use Pro settings":
        file => '/Users/mike/Library/Preferences/com.apple.Terminal.plist',
        key => 'Default Window Settings',
        value => 'Pro',
    }
```

This is because I had multiple settings to set in one file, but names of resources have to be unique across the whole catalog, so I couldn't `mac_plist_value { 'filename': key => 'a', value => 'avalue'} mac_plist_value { 'filename': key => 'b', value => 'bvalue' }`. So either the resource name has to include both the filename and the key, or neither.

Even if this advice works for you, there's still a bug in my code, because `Could not evaluate: no implicit conversion of nil into String` is not an error message that helps you find or fix anything.

**Comment by brownmike** [comment]
Ah, that makes sense. Works great now! Thanks for making this and taking the time to help me out, I really appreciate it. I'm glad you can at least find a small bug in this thread. I'll close this thread, since my original issue is resolved.
